#!/bin/bash 
#PBS -N Kimtest
#PBS -P CBBI1106
#PBS -q normal
#PBS -l select=4:ncpus=24:mpiprocs=24
#PBS -l walltime=16:00:00
#PBS -m be
#PBS -M kimmalloch@sun.ac.za
#PBS -o /mnt/lustre/users/kmalloch/MicroCOSM/stdout.txt 
#PBS -e /mnt/lustre/users/kmalloch/MicroCOSM/stderr.txt


ulimit -s unlimited

module add gcc/5.1.0
module add chpc/gnu/parallel-20180622

NP=`cat ${PBS_NODEFILE} | wc -l`
START=1
((END=96))

echo "Starting job..."
echo "Starting job..." 1>&2

seq ${START} ${END} | parallel --jobs 24 --sshdelay 0.2 --sshloginfile ${PBS_NODEFILE} "echo \"\$( date ): running on \${HOSTNAME}\"; cd /mnt/lustre/users/kmalloch/MicroCOSM/; ./Microsimulation {}"

echo "Ending job..."
echo "Ending job..." 1>&2

